# Generated by Django 4.0.4 on 2022-05-11 03:15

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_pelicula_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=App.models.filepath),
        ),
    ]
